#ifndef __YYTNAME_INDEX_H__
#define __YYTNAME_INDEX_H__

enum YYTNAME_INDEX {
    YY_FLOAT           = 3,
    YY_INT             = 4,
    YY_ID              = 5,
    YY_ASSIGNOP        = 6,
    YY_RELOP           = 7,
    YY_PLUS            = 8,
    YY_MINUS           = 9,
    YY_STAR            = 10,
    YY_DIV             = 11,
    YY_AND             = 12,
    YY_OR              = 13,
    YY_NOT             = 14,
    YY_DOT             = 15,
    YY_TYPE            = 16,
    YY_LB              = 17,
    YY_RB              = 18,
    YY_STRUCT          = 19,
    YY_RETURN          = 20,
    YY_IF              = 21,
    YY_ELSE            = 22,
    YY_WHILE           = 23,
    YY_LP              = 24,
    YY_RP              = 25,
    YY_LC              = 26,
    YY_RC              = 27,
    YY_SEMI            = 28,
    YY_COMMA           = 29,
    YY_Program         = 31,
    YY_ExtDefList      = 32,
    YY_ExtDef          = 33,
    YY_ExtDecList      = 34,
    YY_Specifier       = 35,
    YY_StructSpecifier = 36,
    YY_OptTag          = 37,
    YY_Tag             = 38,
    YY_VarDec          = 39,
    YY_FunDec          = 40,
    YY_ParamDec        = 41,
    YY_VarList         = 42,
    YY_CompSt          = 43,
    YY_StmtList        = 44,
    YY_Stmt            = 45,
    YY_DefList         = 46,
    YY_Def             = 47,
    YY_DecList         = 48,
    YY_Dec             = 49,
    YY_Exp             = 50,
    YY_Args            = 51,
};

#endif
